### PR TITLE
Add Support for OpenCV 4.2, Python 3.8

### LINKED ISSUE #114: Support OpenCV >=4.1
It would be great to support 3.8 for this package.

I've had to install Python 3.6 from the AUR to use it :(

### PR DESCRIPTION
**Pull request by trickeydan**
Fixes #114

The packages are now available upstream.

### CODE REVIEW

**Comment by trickeydan** [comment]
CI is failing because it is detecting **more** markers than before.

**Comment by trickeydan** [comment]
I genuinely have no idea why the tests that are failing now, are failing :(

**Comment by RealOrangeOne** [comment]
I suspect these tests are going to be easier to diagnose by locally poking them rather than CI.

Detecting different markers worries me, and is probably something worth manually checking!

**Comment by trickeydan** [comment]
> I suspect these tests are going to be easier to diagnose by locally poking them rather than CI.
> 
> Detecting different markers worries me, and is probably something worth manually checking!

Do you feel like looking through this together on Saturday?

**Comment by RealOrangeOne** [comment]
> Do you feel like looking through this together on Saturday?

Assuming there's nothing more pressing, sounds like a good use of time :+1:

**Comment by trickeydan** [comment]
This is now blocking progress downstream

**Comment by RealOrangeOne** [comment]
Closed in favour of #256

**Pull request closed without merging**
